@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Plant Floor Manager" as PFM
participant ":System" as System

activate PFM

    PFM -> System : asks to start a new simulation
    activate System

        System --> PFM : requests an identification for the simulation
    deactivate System

    PFM -> System : types requested data
    activate System


    System --> PFM : shows data and requests confirmation
    deactivate System

    PFM -> System : confirms data
    activate System

        System --> PFM : displays operation success and informations
    deactivate System

@enduml