@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "User" as User
participant ":System" as System

activate User

    User -> System : asks to show the flow dependency between work stations and machine routes
    activate System

        System --> User : show the flow dependency between work stations and machine routes
    deactivate System

@enduml