@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title USEI03 - Calculate the total production time for the items

autonumber

actor "Plant Floor Manager" as PFM
participant ":System" as System

activate PFM

    PFM -> System : asks to start a new simulation
    activate System

    System --> PFM : displays the total production time for each item
    deactivate System



@enduml