@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber


Actor ":System" as System

activate System
System -> System : reading of the files
System -> System : data stores in adequate data structures



@enduml