@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
'hide methods

title Domain Model USEI02


class Simulator {
    itemList
    machineList
    createQueues()
    assignItemsToMachines()
}

class Item {
    itemID : ID
    operationList : Qeueu<Operation>
    currentOperation: Operation
    showNextOperation()
}

class PriorityEnum{
    high
    normal
    low
}



class Operation {

}

class Machine{
}

class OperationQueue{
}

Item "1" -- "0..*" Operation : has >
Machine "1" - "         1" Operation: execute >
Item "1" -- "1" PriorityEnum : has >
'Simulator "1" -- "*" Operation : do >
Simulator "1..*" -- "1" OperationQueue: has >
Simulator "1" -- "1..*" Machine : has >
OperationQueue "1" -- "1..*" Item
@enduml