@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Production Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to calculate the execution time of each operation
    activate System

        System --> Employee : shows the time executed by each operation
    deactivate System

@enduml