@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction

class ProductionOrder {
    ProductOrder_ID
    Order_ID
    Product_ID
    StartDate
    EndDate
    Status
    Priority
    ListOfProductBOM_ID
    ListOfProductBOO_ID
}

class ListOfProduct {
    Order_ID
    Product_ID
    Amount_Product
}

class Product {
    Product_ID
    Family_ID
    Name
    Description
    Category
}

class ProductFamily {
    Family_ID
}

class BOM {
    BOM_ID
    Product_ID
    Quantity
}

class Component {
    Component_ID
    Name
    Stock
    StockMin
    Description
}

class Operation {
    Operation_ID
    Description
    Duration
}

class Workstation {
    Workstation_ID
    Sector_ID
    Name
}

class Sector {
    Sector_ID
    Name
    Description
}

class BOO {
    BOO_ID
    sequence
}

ProductionOrder "1" - "1" ListOfProduct : contains >
ListOfProduct "1" - "0..*" Product : contains >
Product "1" - "1" ProductFamily : belongs to >
ProductFamily "1" - "1" BOM : has >
BOM "1" - "0..*" Component : contains >
ProductionOrder "1" - "0..*" Operation : includes >
BOO "1" - "1" Workstation : performed in >
Workstation "1" - "1" Sector : belongs to >
Operation "1" - "0..*" BOO : belongs to >

@enduml
