@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods
left to right direction

class ProductionOrder {
    ProductOrder_ID
    Order_ID
    Product_ID
    StartDate
    EndDate
    Status
    Priority
    ListOfProductBOM_ID
    ListOfProductBOO_ID
}

class ListOfProduct {
    Order_ID
    Product_ID
    Amount_Product
}

class Product {
    Product_ID
    Family_ID
    Name
    Description
    Category
}

class ProductFamily {
    Family_ID
}

class BOM {
    BOM_ID
    Product_ID
    Quantity
}

class Component {
    Component_ID
    Name
    Stock
    StockMin
    Description
}

class Operation {
    Operation_ID
    Description
    Duration
}

class Workstation {
    Workstation_ID
    Sector_ID
    Name
}

class Sector {
    Sector_ID
    Name
    Description
}

class BOO {
    BOO_ID
    sequence
}

class Machines{
    Machine_ID
    Operation_ID
    Description
}

class Company {
    Company_ID
    Name
}

Class Fabric {
    Fabric_ID
    Company_ID
    Address
}

Company "1" - "0..*" Fabric : posses >
Fabric "1" - "0..*" Sector: has >
Sector "1" - "0..*" Workstation: includes >
Workstation "1" - "0..*" Machines: has >
Machines "1" - "1" Operation: does >
Operation "1" ------ "1" BOO: belongs >
ProductFamily "1" - "1" BOO: has >
Product "1" --- "1" ProductFamily : belongs to >
Product "1" - "1" BOM : has >
ListOfProduct "1" - "0..*" Product : contains >
ProductionOrder "1" - "1" ListOfProduct : contains >
Workstation "1" ----- "0..*" ProductionOrder: has >
BOM "1" - "0..*" Component : contains >

@enduml
